# Generated by Django 4.2.3 on 2023-08-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('user_id', models.IntegerField(max_length=6, null=True)),
            ],
        ),
    ]
