# Generated by Django 4.2.3 on 2023-08-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
    ]
