# Generated by Django 4.2.3 on 2023-08-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('brand_id', models.IntegerField(verbose_name='5')),
                ('description', models.TextField(verbose_name='200')),
                ('stock_available', models.BooleanField()),
                ('delivery_time', models.IntegerField(verbose_name='10')),
                ('base_price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('discount', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sub_categories')),
            ],
        ),
    ]
