# Generated by Django 4.2.3 on 2023-08-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.TextField(default=None, verbose_name='400'),
            preserve_default=False,
        ),
    ]
